### ISSUE TITLE
Replace doubleToRawLongBits/doubleToLongBits with reused stack variables.

### ISSUE THREAD

**Issue by mrettig** [vigna/fastutil#108]
Maps that rely on double keys don't reuse a stack variable for doubleToRawLongBits/doubleToLongBits. The double key always has to be converted at least once, so it would improve performance to reuse this value. 

Example of overuse of conversion methods:
```java
public V get(final double k) {
		if ((Double.doubleToLongBits(k) == 0))
			return containsNullKey ? value[n] : defRetValue;
		double curr;
		final double[] key = this.key;
		int pos;
		// The starting point.
		if ((Double.doubleToLongBits(
				curr = key[pos = (int) it.unimi.dsi.fastutil.HashCommon.mix(Double.doubleToRawLongBits(k))
						& mask]) == 0))
			return defRetValue;
		if ((Double.doubleToLongBits(k) == Double.doubleToLongBits(curr)))
			return value[pos];
		// There's always an unused entry.
		while (true) {
			if ((Double.doubleToLongBits(curr = key[pos = (pos + 1) & mask]) == 0))
				return defRetValue;
			if ((Double.doubleToLongBits(k) == Double.doubleToLongBits(curr)))
				return value[pos];
		}
	}
```

**Comment by vigna** [comment]
Indeed you're right. Probably also the double conversion of curr could be avoided.

**Comment by vigna** [comment]
I'm just looking again at the code and clearly doubleToRawLongBits() is wrong. It should be doubleToLongBits(). Accessing the method with different representations of NaN might cause inconsistent behavior (well, if you're doing that you probably have wider problems).

The problem here is that the only solution is to have a copy of each access method for floats and doubles, which frankly I think is overkill because I don't know a single use case.

If performance is really an issue, the user can use a structure holding longs and pass the long representation directly. Not nice, but it solves the problem.
