### ISSUE TITLE
What's the difference between In2ReferenceOpenHashMap and Int2ObjectOpenHashMap?

### ISSUE THREAD

**Issue by RoySunnySean007** [vigna/fastutil#137]
Dear fastutil experts,

Could u please kindly let me know what's the difference between In2ReferenceOpenHashMap and Int2ObjectOpenHashMap?

Really appreciate ur great help in advance!

Thanks,
Roy

**Comment by vigna** [comment]
Issues should be issues—please use the mailing list for questions.

If you just use the key/value association, no difference. But if you use values(), in the first case the collection is by reference, in the second case by value. So if you do a values().contains() the results might be different. Since it is _very_ rare to use values() in such way, just use Int2Object.

**Comment by RoySunnySean007** [comment]
Thx @vigna for ur clear explanation! I will use the mailing list for questions from now on.
