### ISSUE TITLE
wrapped NPE in Long2ObjectOpenHashMap

### ISSUE THREAD

**Issue by biom4st3r** [vigna/fastutil#165]
This seems like the same issue as #109. Only occasionally is `wrapped` not initialized.

https://hatebin.com/fesmjjncjf

**Comment by vigna** [comment]
On September 6, 2020 8:27:54 PM GMT+02:00, biom4st3r <notifications@github.com> wrote:
>This seems like the same issue as #109. Only occasionally is `wrapped`
>not initialized.
>
>https://hatebin.com/fesmjjncjf
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/vigna/fastutil/issues/165

Unit test, please.
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Speiger** [comment]
@vigna the issue is that
https://github.com/vigna/fastutil/blob/master/drv/OpenHashMap.drv#L1706
is only initialized when you remove a entry and the keys were shifted.
https://github.com/vigna/fastutil/blob/master/drv/OpenHashMap.drv#L1764

That means if you try to use the NonLinkedHashMap variant you will ALWAYS have a nullpoint exception because of this line:
https://github.com/vigna/fastutil/blob/master/drv/OpenHashMap.drv#L1727

**Comment by vigna** [comment]
Unit test, please.

**Comment by mernst-github** [comment]
Same in `forEachRemaining`.

```
    new Int2IntOpenHashMap() {
      {
        put(1, 1);
      }
    }.int2IntEntrySet().fastIterator().forEachRemaining(System.out::println);
```

->

```
1=>1
java.lang.NullPointerException
	at it.unimi.dsi.fastutil.ints.Int2IntOpenHashMap$MapIterator.forEachRemaining(Int2IntOpenHashMap.java:797)
	at it.unimi.dsi.fastutil.ints.Int2IntOpenHashMap$FastEntryIterator.forEachRemaining(Int2IntOpenHashMap.java:885)
```

**Comment by vigna** [comment]
Mmmhhh... this does not seem a concurrent modification problem tho. Can you make this in to a unit test?

**Comment by mernst-github** [comment]
No, not a concurrent modification, a plain uninitialized field (didn't realize this issue is about CM). The code above is sufficient to trigger.

**Comment by mernst-github** [comment]
Workaround: `.entrySet().fastForEach` does not throw.

**Comment by vigna** [comment]
Can you file a separate issue please?

**Comment by mernst-github** [comment]
Not sure why. This issue is exactly what the OP describes in https://github.com/vigna/fastutil/issues/165#issuecomment-710089368, and what is also described in #109 . The `wrapped` field in `MapIterator` is only initialized lazily, but the iteration methods access it unchecked. Concurrent modification is only mentioned elsewhere.

**Comment by vigna** [comment]
I'll never understand why people cannot give simple answers and instead enters complex arguments from which one should derive the answer. 🤷🏻‍♂️

This is a problem in the code of forEachRemaining() that was introduced with 8.5.0 two days ago. It has nothing to do with the confusing posts in this issue.

I have to delete this issue, it is a magnet for weirdos.
