### ISSUE TITLE
[Feature request] Pairs

### ISSUE THREAD

**Issue by Arthur-Milchior** [vigna/fastutil#173]
Would you accept Pair<K,V>, similar to https://docs.oracle.com/javase/9/docs/api/javafx/util/Pair.html and https://developer.android.com/reference/android/util/Pair in your codebase ? I use Pairs in my product and would be interested in `PairIntInt` and `PairIntObject<V>`.

If you'd accept such a PR, I would try to create it if I understand the language

**Comment by vigna** [comment]
So, are you sure there are not pairs of primitives around, say in Guava or similar libraries? It seems weird nobody ever tried to implement this. But yes, they could be a nice addition.

**Comment by Arthur-Milchior** [comment]
No, I've not checked all other libraries. A quick search online does not allow me to find anything, and I would suspect that it would be a nice place to put it, given that you already have tools to generate all types. I must admit that I do not know Guava at all, and I didn't check thoroughly through it.
I should not that even finding your library was complex, so i would not be surprised that I missed such a simple set of classes

**Comment by Speiger** [comment]
@Arthur-Milchior @vigna why add a duplicated tuple class? I mean fastutil has already tuples.
new AbstractInt2DoubleMap.BasicEntry(0, 0.2D);

Int2DoubleMap.createTuple(int key, double value) might be a good addition though.

**Comment by incaseoftrouble** [comment]
BasicEntry is neither immutable nor final.

**Comment by Speiger** [comment]
Yeah, but that isn't a bad thing.
There is plenty of cases (especially if you want to have good garbage collection levels) where mutable is nessesary.
It's not a replacement, but I honestly don't know a reason outside of constants where to use Immutable Pairs.

**Comment by incaseoftrouble** [comment]
Uh ... mutability makes GC (in case there are references) and general optimization by the compiler much more difficult. In general, immutability is much advocated for, both for performance as well as design reasons (it is much more difficult to do stupid things with immutable objects).

**Comment by Speiger** [comment]
No? I mean fastiterators in Maps are the best example. They recycle variables because of mutability.
Immutability can help if you implement caches but you can only cache so much, while with mutability you can pool actions.
A good example is my 3d vector for my UI library that is as a helper there to reduce object allocation for data generation for my UI.
I would generate thousands of pairs or triples if it was all immutable. 

Yes Immutable has its place but no its not a ALL way solution. Same with Mutable. But Mutable a much broader range in that regard.

**Comment by incaseoftrouble** [comment]
> No? I mean fastiterators in Maps are the best example. They recycle variables because of mutability.

Even there it isn't clear that the compiler doesn't inline a lot of things. Admittedly, it probably is faster since Java wasn't built with ideas of immutability in mind (however, they are slowly catching up, the upcoming record types will improve *a lot* in that regard, with those I'd bet that immutable types are faster; see basically any functional language for how fast immutable paradigms can be) and primitive assignments are so simple (it is different with references, as I said). Don't forget that (re)assigning variables also has its cost (Java is quite eager with fencing if I recall correctly).

>  I would generate thousands of pairs or triples if it was all immutable.

So what? You can generate *billions* of objects per second. And, again, you don't know how the compiler reuses memory. And you are not forced to use immutable Pairs in such a specific context.

> Yes Immutable has its place but no its not a ALL way solution.

It is for practically all applications of Pair. If you want mutable tuples you have BasicEntry anyway, right?

> Edit: And why i would generate thousands of Immutable objects? I am doing matrix calculations on the CPU because otherwise i would have transfer a lot more data over for what i want out of my toolset. (9 floats to 25 floats per vertex)

So many questions. Why TF do you not use a dedicated library for that? And why do you not use primitive arrays? Why do you think that you need to transfer less memory when you use mutable types? Don't assume, measure. Compilers are one of the most complex black magic pieces of software. But again, this has nothing to to with the Pair discussion (I hope).

In any case, design wise, immutability is such a big plus that I'd gladly incur that performance penalty (if there even is one for most users).

**Comment by Speiger** [comment]
> So many questions. Why TF do you not use a dedicated library for that? 

2 reasons: 1: No library in java supported what i wanted, and there aren't as many as you think and don't have heavy dependencies attached. 2: I wanted to learn how it works in the backend and write myself one.

> Why do you think that you need to transfer less memory when you use mutable types?

You missunderstood me there. Less Memory allocation has to be done because of reusing a mutable variable. (Vec3f transferResult), which i would have to allocate every single time, for each vertex that is generated.

**Comment by incaseoftrouble** [comment]
There are a ton of matrix-vector libraries, even with BLAS/CUDA backends. But, besides the point. Any, as word of advice, don't try to reinvent the wheel. Linear algebra is extremely difficult to do right.

> You missunderstood me there. Less Memory allocation has to be done because of reusing a mutable variable. (Vec3f transferResult), which i would have to allocate every single time, for each vertex that is generated.

Well, again, you are assuming that everytime a new allocation is happening. I guess that Java does this, but I am not sure. Functional languages don't do that, memory is reused. It might well be that newer JVMs figure such things out, too.

In any case, this whole discussion is not contributing to the issue, so lets focus back on the topic, pairs.

I think that a good design choice probably is a) having an interface
```java
XYPair {
 X left();
 Y right();

  static XYPair of(X left, Y right) {
    return new ImmutableXYPair(left, right);
  }
```
with the implementation
```java
ImmutableXYPair implements XYPair {
  private final X left;
  private final Y right;
  // constructor + getters
}
```
and let `BasicEntry` implement `XYPair`.

**Comment by Arthur-Milchior** [comment]
> @Arthur-Milchior @vigna why add a duplicated tuple class? I mean fastutil has already tuples.
> new AbstractInt2DoubleMap.BasicEntry(0, 0.2D);

You're technically correct. This contains everything I need. However, as far as type system goes, it would be pretty strange to state that a function which returns two elements returns a basic entry of a map. Let's say those two elements are X and Y coordinate of a click, it has semantically nothing to do with map, and I would not want that someone joining the project tries to figure out which map this is coming from.
However, if we want to avoid code duplication, it may make sens to state that 
`AbstractInt2DoubleMap.BasicEntry` is another name for `ImmutableIntDoublePair` (or whatever names you decide to choose).

> Int2DoubleMap.createTuple(int key, double value) might be a good addition though.

Android's Pair library has a function to create pairs. I should admit that I do not know why `createPair` would be better than `new Pair`

**Comment by incaseoftrouble** [comment]
> Android's Pair library has a function to create pairs. I should admit that I do not know why createPair would be better than new Pair

Factory methods hide the implementation (you can return `Pair` instead of `PairImplementation`) and you can perform additional validation (however not applicable here). In particular, it solves the "naming" issue. If you let `BasicEntry` implement pair, you can simply return `BasicEntry` without anyone wondering :-)

>  AbstractInt2DoubleMap.BasicEntry is another name for ImmutableIntDoublePair (or whatever names you decide to choose).

`BasicEntry` would be mutable though, but jeah.

> Edit: I know that it's sometime considered bad practice to return a pair instead of creating a small class specilazed for the return value of the function. I don't want to do it each time I return two values, it does not really seems worth the extra code added. But I might understand you don't want to encourage what is sometime considered to be a bad behaviour

Having generic `Pair`s is perfectly fine (especially in this particular type-specific case). Pairs / Tuples are such elementary concepts.

**Comment by Speiger** [comment]
> Well, again, you are assuming that everytime a new allocation is happening. I guess that Java does this, but I am not sure. Functional languages don't do that, memory is reused. It might well be that newer JVMs figure such things out, too.

Everything that starts with "new" allocates memory. If it is now stack memory or heap memory it is not know. The compiler decides that but it is sure that it will allocate memory. the java compiler actually does not change much code, it might resort it if there is not dependencies or synchronization but from what i have experienced especially with mc going immutable on their coordinate system is that garbage collection rises. In MCs example it was i think multiple gigabytes of allocation in a mass worldgneration test that took up 50% of all allocations in Java and that was 60 second JavaMission Control allocation recording.

**Comment by incaseoftrouble** [comment]
> Everything that starts with "new" allocates memory.

No, the GC does not immediately free unused memory back to the system, similarly `new` does not result in a memory allocation call. See for example [here](https://softwareengineering.stackexchange.com/questions/149563/should-we-avoid-object-creation-in-java) or [here](https://www.ibm.com/developerworks/java/library/j-jtp04223/index.html) for some additional myths.

Also isn't minecraft running on some ancient Java version (8 oder something?). A lot has happened since then.

**Comment by Speiger** [comment]
> No, the GC does not immediately free unused memory back to the system, similarly new does not result in a memory allocation call. See for example here or here for some additional myths.
Also isn't minecraft running on some ancient Java version (8 oder something?). A lot has happened since then.

Its running on java8 yes. I haven't tried newer versions yet. And fastutil is also still running on java8 (actually 7 if we look at all the holes that we see) So my comparison is to that.

I doubt that java deallocates/recycles memory that efficently especially since in the example i saw it was creating gigabytes per "couple (2-3)"seconds. I am not sure how likely that is.

I know if you write code memory efficient it does not actually allocate memory while still recycling memory but in such a scale, don't trust the JVM/Compiler. (In my engine it say it is allocting 200kb a second yet the memory usage is not going up so it is recycing data quickly enough.

I know it is a selfinvalidating statement, but in my case i am pooling a lot in my engine and  try to avoid allocations or optimize them a lot, and in mc it is not doing that at all.
So this is where: Immutable vs mutable comes into play. I have made a lot of bad experience with Immutable.

**Comment by incaseoftrouble** [comment]
> Its running on java8 yes. I haven't tried newer versions yet. And fastutil is also still running on java8 (actually 7 if we look at all the holes that we see) So my comparison is to that.

Compile time version != runtime time version. Java uses JIT compilation.

> I doubt that java deallocates/recycles memory that efficently especially since in the example i saw it was creating gigabytes per "couple (2-3)"seconds. I am not sure how likely that is.

That seems very slow. Object allocation is, for all intents and purposes, one of the fastest operations you can even have on JVM. It is even faster than on C++ for a lot of applications, since less system calls are needed. Also, let me quote:

> Current GC algorithms are actually optimized for creating many many small objects that are short lived, that is basically the 99% heuristic for Java objects in every program. Attempts at Object Pooling will actually make the JVM perform worse in most cases.

By pooling, you are just throwing obstacles into the way of the GC. It only makes sense to pool if you throroughly tested your code and are sure that pooling helps (and not some other side effect).

Anyway, we are deviating, again. I think `Pair` and maybe `MutablePair` interfaces would be nice, with appropriate implementations + factory methods (see my above proposal).

**Comment by vigna** [comment]
@Speiger, at this point you are generating just an infinite amount of noise. Nobody is interested in optimizing everything for MC running on Java 8. I suggest that you restrict your comments to correct technical statements that have general validity. Otherwise, I'll have to block you. You are seriously impeding a sensible discussion on a number of issues.

**Comment by Speiger** [comment]
> Compile time version != runtime time version. Java uses JIT compilation.

Yes but the JIT runs in the JVM.

> That seems very slow. Object allocation is, for all intents and purposes, one of the fastest operations you can even have on JVM. It is even faster than on C++ for a lot of applications, since less system calls are needed. Also, let me quote:

If you would see the code you would puke. It is not efficient at all.

> By pooling, you are just throwing obstacles into the way of the GC. It only makes sense to pool if you throroughly tested your code and are sure that pooling helps (and not some other side effect).

Not really. When i started pooling objects GC actually got faster since references were still present and objects could be faster evaluated for removal. This is what I have experienced.

> Anyway, we are deviating, again. I think Pair and maybe MutablePair interfaces would be nice, with appropriate implementations + factory methods (see my above proposal).

+1

> @Speiger, at this point you are generating just an infinite amount of noise. Nobody is interested in optimizing everything for MC running on Java 8. I suggest that you restrict your comments to correct technical statements that have general validity. Otherwise, I'll have to block you. You are seriously impeding a sensible discussion on a number of issues.

Never said that I intendet optimizing mc, I am using that as a example why Immutability can cause issues if you are not careful.
Well incaseoftrouble i assume that we have now to stop our disscussions that I actually found very interesting.

last comment from my side then.

**Comment by avivmu** [comment]
If you can (and you should, IMO) use [Java Records](https://openjdk.java.net/jeps/395), started at JDK14 and continued in JDK15 as a preview feature, it will be implement as a feature in JDK16.
With records, declaring a primitive _ordered_ pair is achieved with one line:
`public record OrderedIntPair(int left, int right) {
}`
also:
`public record OrderedIntObjPair<T>(int left, T right) {
}`

**Comment by vigna** [comment]
I know,  but we're at java 8 here ;).

**Comment by incaseoftrouble** [comment]
Just to add on that: Project Valhalla / JEP 218 (once implemented) will probably make this whole library obsolete. But its a long road till then.

For records to be used we'd at least have to wait until they are part of the current standard language release (not a preview feature)

**Comment by vigna** [comment]
> Just to add on that: Project Valhalla / JEP 218 (once implemented) will probably make this whole library obsolete. But its a long road till then.

Mmmh. Not sure:

> Non-Goals
> It is not a goal of this effort to produce fully reified generics.

**Comment by incaseoftrouble** [comment]
`s/whole/a lot/g` :-) We don't know what exactly will be implemented there, anyway. But I'd guess that if records and primitives can be used as generics, the reference collection implementations will fully support them.

**Comment by vigna** [comment]
I was a bit under pressure as I need this elsewhere, so I tried and the result is in c9c12c3cbf7. 

We now have a pair interface, mutable pairs and immutable pairs. Entries from maps have been retrofitted to implement the suitable pair interface. Accessors obey three type of language: left/right (preferred), first/second, key/value. You just have to implement left/right. There are .of() methods in interfaces and in implementations. A completely generic Pair interface lives in it.unimi.dsi.fastutil.

I'd love to get comments on the design and the implementation!

**Comment by vigna** [comment]
I have also added in 026a1f173b5 a facility for sorted pairs. That can be useful if you have to represent unordered pairs by canonicalization. I need it for some WebGraph adapters I'm writing for JGraphT.

**Comment by incaseoftrouble** [comment]
A random thought while reading: Maybe define a macro for the
```java
	/** {@inheritDoc}
	 * @deprecated Please use the corresponding type-specific method instead.
	 */
	@SuppressWarnings("deprecation")
	@Deprecated
	@Override
```
block. Its the same everywhere :-) Otherwise fine; I guess that it makes sense to have "mutable by default" interfaces and specialize to immutable. But then the `Pair` should not default the setters I think, rather `ImmutablePair` should add these defaults. Objects implementing `Pair` and not `ImmutablePair` should be mutable or explicitly decide that they are not I think.

**Comment by Arthur-Milchior** [comment]
Thank you very much for taking care of it. 

I must admit I'm slightly confused by the hierarchy.
drv/ImmutablePair.drv implements either drv/Pair.drv or src/it/unimi/dsi/fastutil/Pair.java and drv/Pair.drv implements src/it/unimi/dsi/fastutil/Pair.java
This means that ImmutablePairs have a setter method, which throws an exception. 

I totally understand why you want inheritance. It's important for code that only use the getter to have a way to accept both mutable and imutable pairs. I also understand that using Pair.java allows to have once and for all the definition of first, and key using the definition of left
What I don't understand is why are the setters in `Pair`. 
Is there a problem with creating an interface src/it/unimi/dsi/fastutil/MutablePair.java which inherits src/it/unimi/dsi/fastutil/Pair.java and contains all the setters, removing the setters from src/it/unimi/dsi/fastutil/Pair.java. Then 
drv/MutablePair.drv could extends both drv/Pair.drv and src/it/unimi/dsi/fastutil/MutablePair.java. it seems that Java handle the diamond problem correctly and that this inheritance scheme would not create any trouble.

I strongly suspect that doing so will avoid a lot of bugs, due to people seeing that a setter function is available thanks to autocomplete and not checking whether it is actually implemented.

If we want the name "ImmutablePair", then we can always create an ImmutablePair that inherits from Pair and adds no other feature.

**Comment by incaseoftrouble** [comment]
@Arthur-Milchior I agree with your thoughts, just for context: One point for the current design is that Java's Collection API works the same way. You have mutators on the base interface and throw exception if immutable. This is stupid, but can't be changed now. A "solution" is given by explicitly returning "ImmutablePair" (as Guava recommends for `ImmutableXY`). I am not sure if consistency is worth the design flaw here though, too.

**Comment by vigna** [comment]
Well, Guava does the same with immutable classes (maybe for compatibility with the JDK?).

Can someone give an example of widely-used collection framework not using the same strategy? I perfectly understand the issue with the completion, but having a single Pair interface has the enormous advantage that we do not have to specify whether we return immutable or mutable pairs. In fact, the idea that a MutablePair inherits from ImmutablePair is, from the viewpoint of design-by-contract, quite crazy: you have an interface that specifies immutability, and then a derived interface contradicts the same idea...

**Comment by vigna** [comment]
BTW, nothing is set in stone!

**Comment by vigna** [comment]
BTW, we can deprecate the mutation methods in the immutable implementations. That should help with the completion.

**Comment by incaseoftrouble** [comment]
> In fact, the idea that a MutablePair inherits from ImmutablePair is, from the viewpoint of design-by-contract, quite crazy: you have an interface that specifies immutability, and then a derived interface contradicts the same idea...

I think the idea would be that you have a `Pair` base class which defines getters, an `ImmutablePair extends Pair` which signifies complete immutability, and `MutablePair extends Pair` which defines setters. Stuff like entries where one is mutable and one is not extend `Pair` and add setters on their own (which makes them unusable for methods taking `MutablePair` though ...). I guess the last thing is the main point of having setters on the base methods. Even if you have a pair which does not fully support mutation, you can still throw it at something mutating only, e.g., the left part of the pair. Its a bit like duck-typing / python style in that sense.

> BTW, we can deprecate the mutation methods in the immutable implementations. That should help with the completion.

I think the main point is that the `Pair` type will often be used blindly as also supporting mutation. If you know you are getting an `ImmutablePair` its probably more obvious (but deprecation certainly helps!)

**Comment by vigna** [comment]
Another issue that makes me unconfortable is that this adds ~200 classes. No joke. There are Mutable/Immutable interfaces for Pairs and SortedPairs.

**Comment by vigna** [comment]
I must say that whenever I look immutability is always an implementation, not an interface.

**Comment by incaseoftrouble** [comment]
> I must say that whenever I look immutability is always an implementation issue, not an interface issue.

Jeah, its the Java way™ of handling immutability I fell like.

> Another issue that makes me uncomfortable is that this adds ~200 classes. No joke. There are Mutable/Immutable interfaces for Pairs and SortedPairs.

Well you could in theory have a generic `Immutable` marker interface (yes marker interfaces are bad ...) that is applied to all immutable types and only have `Pair` base class + `MutablePair extends Pair`. But its still a lot of classes and by now Java people probably are just to this "mutability is optional" approach.

**Comment by vigna** [comment]
Also, I've programming in Java for >20y at this point and never, once if my life I got an exception because I tried to mutate something I shouldn't have. I cannot really imagine the situation in which that could happen.

**Comment by Arthur-Milchior** [comment]
> Also, I've been programming in Java for >20y at this point and never once if my life I got an exception because I tried to mutate something I shouldn't have. I cannot really imagine the situation in which that could happen.

I've spent 6 years teaching java to first and second year student in my past jobs. I guess this lead to very different feelings about what can be expected from people programming. 

It's also quite possible that I just don't know java enough to know what's done usually in java. I've worked with a single java project outside of university. So if you believe this approach is the more standard one as far as java goes, that's fine. I still stand by my remark, but I've no more argument in favour of it, and if it seems a bad idea to more experienced devs', I won't insist.

Thanks @incaseoftrouble for explaining my idea better than I did. Even if we don't go this way, I'm happy to know that the exact idea I tried to give was considered.

Concerning the number of class, happily, in AnkiDroid (where I expect to use it) removal of all unused classes is automated when we generate the app, so that would not be a problem for me. But I totally understand that it is not an universal rule.

**Comment by vigna** [comment]
Well, I taught C for 12 years and Java for 10 years both at first-year and graduate students, so I had my share of experience, believe me.

In any case, I should let you see my Eclipse trying to recompile 2400 classes 😂. It is not a matter of jar size—it's just a matter of maneuverability.

So, for a Java programmer used to the structure of the JDK, there's an interface with optional mutable methods, and then there are mutable and immutable implementations. It is important, in designing software, to adhere to the principle of minimum surprise—a completely different design might surprise someone experienced, and fastutil is definitely not for the faint-at-heart.

**Comment by Arthur-Milchior** [comment]
Speaking of least surprise: I was surprised to see setters without `set` prefix.

Thanks for taking the time to add pairs and considering my remarks.

**Comment by vigna** [comment]
Yeah, that's a vexata quaestio since ever. Even in the JDK depending on the programmer they used a different standard. For example, FileChannel.position(long)/FileChannel.position() use the "argument/no argument" standard, whereas Map.Entry uses the "get/set" standard. Personally I've always preferred the "argument/no argument" way and I'm happy when I find it.
