### ISSUE TITLE
Make iterators fail-fast on concurrent modification

### ISSUE THREAD

**Issue by magneticflux-** [vigna/fastutil#179]
Currently, iterators from this library throw unrelated exceptions when a concurrent modification occurs. This is undesirable, as it obscures the true causes of bugs and can cause spurious issues.

I propose keeping a count of modifications, similar to what JDK classes do, and checking against the last known number of modifications when iterating. This does not guarantee throwing a CME in the presence of multiple threads, but it does guarantee modification of the collection inside a loop in a single-threaded context.

I believe there are a few instances where the lack of a `ConcurrentModificationException` obscured the root cause over the years:

- (2017) https://groups.google.com/g/fastutil/c/8nmHfHDcMDs
- (2018) https://github.com/vigna/fastutil/issues/109
- (2020) https://github.com/vigna/fastutil/issues/165

**Comment by vigna** [comment]
As you can imagine, this was weighted for some time in the design and implementation. Given that fastutil's main priority is efficiency, an increment and a test were deemed too costly for a check that is not complete: you might still get spurious exceptions—there's no guarantee you'll catch the concurrent modification (more than fail-fast, the JDK structures should be called hopefully-fail-fast). The code is really mature and by now I reject any bug report about exception that does not come with a unit test. In the end they all turned out to be caused by concurrent modifications.

**Comment by incaseoftrouble** [comment]
As a side note: What maybe could be done is an assert with sideeffects (basically put the modification counting into an assert). While asserts should be side-effect free in general, datastructure integrity is something that often needs side effects to be checked.
