### ISSUE TITLE
fastForEach does not support setValue though fastIterator does

### ISSUE THREAD

**Issue by faucct** [vigna/fastutil#288]
Is this intentional?

**Comment by vigna** [comment]
I didn't implement that part, so I cannot answer directly. But I think it wasn't intentional.

The problem is that fastIterator() uses an Entry() that remembers the position where it is located in the hash table, and thus can implement without problems setValue(). The forEach()/fastForEach()/etc. methods use a BasicEntry which has no such support.

I don't think it should be difficult to implement. I'll have a look at it.

**Comment by vigna** [comment]
Commit 4566dfe0ef5f4df77546a38094e4a3689df0fa1a should solve the problem. Please reopen this issue if it doesn't work for you.

**Comment by faucct** [comment]
Thanks!
