### ISSUE TITLE
Left over benchmark code?

### ISSUE THREAD

**Issue by cdman** [vigna/fastutil#34]
I think there is some left-over benchmark code here: https://github.com/vigna/fastutil/blob/14a7b9137a62d39096519f2e388234e0dee4e557/src/it/unimi/dsi/fastutil/BigArrays.java#L562

**Comment by vigna** [comment]
Well, it's not a leftover—you can actually run it! :)

But interestingly enough, running it I found a stupid bug (the start time of the last benchmark was not set) who led me to the belief (stated in the old docs) that using an additional index in scanning instead of using index(d, s) would have been much slower. I just fixed the docs few days ago running an independent test, and was wondering how *ever* I could get convinced of that. Now I know... thanks! :)
