### ISSUE TITLE
Some methods in SynchronizedMap don't use synchronization

### ISSUE THREAD

**Issue by damluar** [vigna/fastutil#46]
I've looked into source code for SynchronizedMap and I'm not sure it's implemented correctly:

```
public LongSet keySet() {
    if ( keys == null ) keys = LongSets.synchronize( map.keySet(), sync );
        return keys;
    }
}
```

If multiple threads call this method at the same time, than mutliple `LongSet` instances might be created. They are thread-safe, so nothing bad will happen, but still it feels not right.

Moreover another method never sets the `values` variable:

```
public ObjectCollection<V> values() {
    if ( values == null ) return ObjectCollections.synchronize( map.values(), sync );
    return values;
}
```

Java's implementation in `java.util.Collections.SynchronizedMap` synchronizes the whole method:

```
public Set<K> keySet() {
    synchronized (mutex) {
        if (keySet==null)
            keySet = new SynchronizedSet<>(m.keySet(), mutex);
        return keySet;
    }
}
```

**Comment by vigna** [comment]
You're right, and it looks like a copy-and-paste thing, because UnmodifiableMap has the same problem.

Both "bugs" are efficiency bugs—the implementation is semantically correct. Of course the value thing must be fixed.

When I was writing these classes (like, 15 years ago? LOL), synchronization was very expensive. So it seemed to be sensible to create in some race condition two view objects (both very lightweight). I agree that the design for current JVMs should be different. I'll fix it.
