### ISSUE TITLE
Insert-Performance in Object2ObjectOpenHashMap depending on insertion order

### ISSUE THREAD

**Issue by mrieser** [vigna/fastutil#53]
I'm using an ``Object2ObjectOpenHashMap`` as an internal data structure. When my program ends, I write out the content to disk (using custom serialization code, iterating over the map). When the program the next time starts, it reads the data back in from disk, inserting the objects again into the map. I realized that reading the data back in is much slower than inserting the objects in the first round. After some testing, I found out the following:

- Inserting objects into an ``Object2ObjectOpenHashMap`` in "random" order requires some amount of calls to ``equals()`` in the inserted Objects.
- Inserting objects into an ``Object2ObjectOpenHashMap`` in the order as they are returned from the iterator from another ``Object2ObjectOpenHashMap``, it requires many more calls to ``equals()`` in the inserted Objects (at least one magnitude more calls).

If the ``equals()`` method does a bit of logic, it has a huge impact on performance.

I'll attach a short piece of code that demonstrates the problem, inserting Strings into the Map (Actually, ``WrappedString``s so I'm able to count the number of ``equals()`` invocations). Inserting the 2 million Strings the first time requires about 5 million ``equal()`` calls, while inserting them the second time requires about 180 million ``equal()`` calls.

It reminds me a bit of the problem in Java's ``HashMap`` a while ago (Java 7?) where it was said inserting objects in a special order could lead to Denial of Service attacks due to very poor performance in such cases.

[InsertTest.java.txt](https://github.com/vigna/fastutil/files/705845/InsertTest.java.txt)

**Comment by vigna** [comment]
What you're seeing is an artifact we in fact discussed with David Weiss (of HPPC fame) some time ago. It is due to correlation in entry location when an expansion happens. If you make this simple change:

 Object2ObjectMap<WrappedString, String> map2 = new Object2ObjectOpenHashMap<>(map1.size());

you'll see nothing bad happens. What surprises me is that you think you observe this effect when loading. This is strange, because the map is pre-sized. Did you actually measure the number of equals() during a load?

**Comment by mrieser** [comment]
Thanks for the feedback. I deliberately did *not* pre-size the second map to have the test case comparable to the first one. Also, in my real-world use case where I observed the problem first, I have no knowledge of how many entries I'll have to read in, so I cannot pre-size the map efficiently.

**Comment by vigna** [comment]
Oh I see. I thought you were talking about serialization.

There are no easy solutions here. You might randomize the order of the saved data. Or save the size of data.

**Comment by lemire** [comment]
@mrieser I'd be tempted to ask... have you tried with other linear-probing implementation? I'd submit to you that if they all share this characteristic then it is not an issue of the library but an issue of the data structure.

**Comment by vigna** [comment]
Note that there's a solution: include the map size in the hash scrambling function. The problem is that the correlation actually _helps_ when rehashing, and you lose some 5% in efficiency if you scramble. Dawid and I discussed the situation at length and we concluded that there was no real use case in which this would have been a real problem. But we did not think of handmade serialization.

**Comment by lemire** [comment]
@mrieser  Could you explain your use case? How do you end up with keys that come straight from a hash table, but you have no way of knowing how many there are? If you serialized it by hand, I submit to you that you should make sure that you have easy access to the key count if you care about performance.

**Comment by mrieser** [comment]
@lemire: no, haven't tested other libraries, but I'm happy to do so. Do you know which other libraries offer similar (linear-probing) implementations?

**Comment by mrieser** [comment]
@vigna: Basically, I use the Map as internal data structure, and read/write the data in some specific data format, where the order of the data is not important, as the data is usually accessed by a key. So I just used the iterator to write out the data. Will try to randomize the order somehow when writing the data out.

**Comment by lemire** [comment]
@mrieser There is a benchmark...

http://java-performance.info/large-hashmap-overview-jdk-fastutil-goldman-sachs-hppc-koloboke-trove/

It includes a lot of competitors. Not all of them use linear probing, but some others do for sure.

**Comment by mrieser** [comment]
Okay, more details about my use case:
I read in a lot of data, for example about buildings, each having an identifier, a centroid coordinate, and additional attributes. The format the data has to be in is well specified (it's a custom XML serialization, specified by a DTD). This format (sadly) does not include a count, it's just specified to contain a list. So all I can do is to just parse the XML until I hit the corresponding end-tag.
My application then works with the data, it might modify or filter it, calculate/add new attributes, etc. In the end, the data is written out again in the same format.

Next to the map for lookups by identifier I also maintain a spatial data structure for spatial lookups, so maybe I can also just try to use the iterator-order of that when writing the data out again.

**Comment by lemire** [comment]
@mrieser 

If the data is read from disk or a network, it is likely that the bulk of the wall-clock time is due to the IO, not the CPU. Correct?

**Comment by vigna** [comment]
Actually not in this case, as the slowdown is quadratic. A tactic might be to presize a very large map and then trim(). Do you have a reasonable upper bound on the size at hand when you read the data?

**Comment by lemire** [comment]
@mrieser @vigna 

So then scan all of the data once, getting the count. That's linear time and requires no allocation. Then rescan the data a second time with full knowledge of the count. That works as long as the XML data is available to be scanned twice.

**Comment by vigna** [comment]
If you are willing to write a few lines of code, just subclass and write an iterator that, say, instead of scanning linearly the backing array increases its current position by array.length / 8 + 1.  That should permute the entries enough to avoid any problem. Of course any odd number will work.

**Comment by mrieser** [comment]
@lemire: if it would have been bound by IO time, I wouldn't have noticed the problem ;-)  In my case, the first time I loaded the data, it took about 20 seconds (reading from disk/ssd), the second time it was more like 5 minutes.

@vigna: an upper bound is hard to define, because the data files can be user-provided. I could try to make an estimation based on the file size in bytes.

Parsing it twice would technically solve the problem, although probably at quite some overhead.
An alternative might be to read the data first into an ArrayList, then sort it based on some criteria/attribute, and then insert it into the map based on the sorted order from the list. Sorting it in memory should take less time than reading/parsing it twice, and the memory overhead should be manageable (basically an oversized array of object pointers, so even for 2 million entries, it would be at worst 4m*4bytes = 16 MB).

**Comment by lemire** [comment]
@vigna @mrieser  Does the problem persist when you adjust the load factor?

**Comment by vigna** [comment]
Yes, it's independent. Well, it improves of course, but it's all a problem of correlation of the positions of an entry in a table of 2^n and a table with 2^(n+1) elements.

BTW, the really best thing would be to enumerate the element at steps approximately of the square root of the table size. It could be something like (in a hypothetical subclass):

jump = mask >>> (Integer.numberOfTrailingZeros(n) >>> 1);

Then you enumerate the positions in the table using p = (p + jump) & mask for size times, skipping empty entries.

**Comment by lemire** [comment]
@vigna  Where does the quadratic factor comes from?

I have not looked your code, but I assume it is just textbook linear probing... with many years of engineering.

Obviously, if my hash function is terrible, I can be in trouble. But that's not what seems to be happening, otherwise you would have said so.

Ok.

Suppose my initial capacity is N. I load up N/2 values (load factor =0.5). Ok. 

I have to expand. Now I allocate an array twice the size. Fine. I need to reinsert my N/2 values. Sadly, they will almost all get stuck in the first half of my new array. That means that I have more probing than otherwise. Ok. But reinserting these N/2 values cannot take longer than initially inserting them. If anything, you should be getting slightly fewer collisions, so a bit less probing.

And so forth. So insertion time *won't be constant time*. That much is clear. But quadratic???

I do realize that, maybe, linear probing **can be** quadratic in the worst possible case... but I don't see why it would happen in the scenario described here.

Maybe I am being an idiot and it is obvious...

**Comment by vigna** [comment]
I sent this to Dawid as a puzzle some time ago LOL. So, the problem is that if you add elements in the array order, you are pushing elements in adversarially WRT conflict-chain generation. This is true of every linear probing implementation—all implementations I know do the same—unless you condition your hash function on the table size. Note that textbooks don't tell you anything about pouring elements from one collection into another, or about serialization.

Now, when you rehash this correlation is _good_. As you enumerate elements from the table, you still store elements essentially at two different locations that slowly progress through the first and second half of the new array. And the cache is so happy.

The problem comes when you are reading elements from another table. At that point, every block sized as a power of 2 "hits" the same spots, in the same order, in the destination array. The conflicts chain that are created in this way are of linear, not constant, size. At that point every operation becomes linear.

**Comment by lemire** [comment]
Thanks for educating me. Ok so when I wrote "reinserting these N/2 values cannot take longer than initially inserting them", I was wrong... you have a quadratic factor in terms of the maximal probing distance. Or something.
