### ISSUE TITLE
LongOpenHashSet gets stuck in infinite loop when removing if load factor is 1.0f and trim has been called

### ISSUE THREAD

**Issue by jamonkko** [vigna/fastutil#6]
Here is how to reproduce with fastutil-7.0.8:

```java
import it.unimi.dsi.fastutil.longs.LongOpenHashSet;

public class LongOpenHashSetInfiniteLoopInRemove {

    public static void main(String[] args) {
        LongOpenHashSet set = new LongOpenHashSet(4, 1.0f); // Changing load factor to 0.9f makes this work
        set.add(1);
        set.add(2);
        set.add(3);

        set.remove(2);
        set.trim();  // Removing this trim makes this work

        System.out.println("Remove 1 starts...");
        set.remove(1); // Will hang inside this call
        System.out.println("Remove 1 done!");
    }
}
```

Running:
```
javac -cp fastutil-7.0.8.jar LongOpenHashSetInfiniteLoopInRemove.java
java -cp ".:./fastutil-7.0.8.jar" LongOpenHashSetInfiniteLoopInRemove
```

**Comment by vigna** [comment]
> On 13 Nov 2015, at 11:40, jamonkko <notifications@github.com> wrote:
> 
> Here is how to reproduce with fastutil-7.0.8:
> 

Sorry. No. That's wrong. Everything is designed to work with f=1.

The problem is in trim(): this check

	if ( l >= n ) return true;

should actually be this check:

	if ( l >= n || size > maxFill( l, f ) ) return true;

When f=1 and n is ridiculously small (e.g., 4), it might happen that the estimated array size is smaller than the current one, *but* the maximum fill of the estimated array size is smaller than the current number of elements (due to the minimization with n - 1 of maxFill() to guarantee a free slot).

Thanks for the report!

Ciao,

					seba

**Comment by vigna** [comment]
Would you email me your exact name to be quoted on the CHANGES file?
