### ISSUE TITLE
Map and Entry toString()

### ISSUE THREAD

**Issue by leventov** [vigna/fastutil#63]
`Map.Entry.toString()` is de-facto specified as `key=value`, and `Map.toString()` as `{k1=v1,k2=v2, ...}`. A lot of code here and there rely on this form. Fastutil uses `=>` as delimiter.

**Comment by pburka** [comment]
I don't object to @vigna changing the `toString()` implementation, but I think it's incorrect to claim that `key=value` is a _de facto_ standard. Apache commons [Pair](http://commons.apache.org/proper/commons-lang/apidocs/src-html/org/apache/commons/lang3/tuple/Pair.html) (which implements `Map.Entry`) uses `(key,value)`, for example.

**Comment by lemire** [comment]
Do you guys use ``toString()`` as a form of serialization? 

Why not use an actual standard like JSON?

**Comment by vigna** [comment]
As other pointed out, this is not standardized. I'm a mathematician: Having a mapping denoted by = it's so painful I can't describe. It's crazy,, ridiculous,  preposterous.

**Comment by qwwdfsad** [comment]
>As other pointed out, this is not standardized

fastutil is frequently used (in my practice) as drop-in replacement for `java.util.*`, so it would be nice if such details as `toString()` shape were preserved.

I've step up in this issue during migration of holders for bunch of counters to fastutil, which were tested using `toString()` (it was a bad idea in the first place, but I think that for supplementary code it was easiest way for author to test it). Such small thing decreased development and shipment speed and I guess I'm not the only one who had this issue.

I think it's good idea to re-open this issue and fix it if there will be enough requests for it.

**Comment by frajt** [comment]
Is there any chance to re-open this issue to follow the common toString() implementations?

We are just selecting a replacement for the Trove library which is used in our code base since 2004. Some years back we covered all with Guave Map/Set Test Suite to keep all as much consistent as possible between various map/set implementations in use. Surprisingly FastUtil map fails immediately on toString() so that the test require CollectionFeature.NON_STANDARD_TOSTRING to succeed. It is very hard to estimate where in a 3 milion line code base this is going to create an issue. 

What is actually the rationale behind this?

**Comment by vigna** [comment]
As I explained, = is a nonsensical sign from a mathematical viewpoint. Functions are not symmetric.

**Comment by frajt** [comment]
The toString() on all Collections/Maps is just an informative, debugging output not being able to provide any mathematical, logical, practical value as there is no escaping of keys/values printed. What is then your mathematical viewpoint on your SingletonMap("+-=>", "<=>^3&5").toString() output? And the FastUtil Collections using {} instead of [] has yet another mathematical viewpoint? Why FastUtils hashCodes follow JDK implementations but the toStrings cannot? Neither of it is a part of the interface specification but everybody does follow what was typed in JDK code in the last century. There is no single benefit of toString() being different. It creates only troubles. It is 5 minutes work to get it right. I really don't get it.

**Comment by vigna** [comment]
I can see that!
