### ISSUE TITLE
Equivalent to Guava's RangeMap?

### ISSUE THREAD

**Issue by dustContributor** [vigna/fastutil#76]
Hi! I've been looking for something like Guava's RangeMap https://google.github.io/guava/releases/16.0/api/docs/com/google/common/collect/RangeMap.html

ie, something that lets me map non-overlapping contiguous ranges of numbers to something else. In my particular use case, I want to map sections of a StringBuilder to different text "kinds". So I'd have a map that lets me map the range [0, 15) to text kind 2, and range [15, 28) to kind 1, for example.

RangeMap seems like it does what I want but it uses Range objects with Objects as elements delimiting the start/end of the range. It'd be nice to have a flat primitive version of that, like fastutil does, with an interface like:

```java
// With int values.
// Any number in the range [keyStart, keyEnd) would return the value.
void put (int keyStart, int keyEnd, int value);
int get(int keyStart, int keyEnd);
// With object values
void put (int keyStart, int keyEnd, T value);
T get(int keyStart, int keyEnd);
```

Makes sense?

**Comment by vigna** [comment]
Yes, but it's a definitely non-trivial effort. But Guava's uses Apache's licence, too, so probably it's possible to "fastutilize" their code easily.

**Comment by dustContributor** [comment]
Thanks for considering it!

I think I can get "sort-of" that behavior with a Long2Int hash map, where I pack int ranges into a single long, implementing a custom Strategy equals that unpacks them and compares them. I have to test it but it looks like it could work.

**Comment by dustContributor** [comment]
Nope, I was terribly wrong. I think since a single value's hash code doesn't returns the same value as the range, the map tries in a different bucket, and doesn't finds the range. And I doubt i'll find a hash function that can map arbitrary ranges like that :smile:

**Comment by incaseoftrouble** [comment]
One more comment: For this to be relevant directly in fastutil, it probably should work for all primitive keys, i.e. it should be possible to have a `Long2CharRangeMap`.

I think that hash-based methods won't get you far I think, since proper hashes will mess up any ordering. For ranges to make sense, you need to have an ordering anyway, so lets use this. My first idea for implementing this would be to store the ranges in a sorted map. For example, if you consider a priority queue, you'd "only" have to check the next smaller and larger elements for overlap and then act accordingly.
